[theme]
base = "dark"
primaryColor = "#EAE0C8"
backgroundColor = "#202833"
secondaryBackgroundColor = "#18202A"
textColor = "#EAE0C8"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
